## 3.2 张量：多维数组

### 3.2.1 从Python列表到PyTorch张量

In [1]:
a = [1.0, 2.0, 1.0]

In [2]:
a[0]

1.0

In [3]:
a[2] = 3.0

In [4]:
a

[1.0, 2.0, 3.0]

### 3.2.2 构造第一个张量

In [5]:
import torch
a = torch.ones(3)
a   

tensor([1., 1., 1.])

In [6]:
a[1]

tensor(1.)

In [7]:
float(a[1])

1.0

In [9]:
a[2] = 2.0
a

tensor([1., 1., 2.])

### 3.2.3 张量的本质

points = torch.zeros(6)
points[0] = 4.0
points[1] = 1.0
points[2] = 5.0
points[3] = 3.0
points[4] = 2.0
points[5] = 1.0

In [10]:
points = torch.tensor([4.0, 1.0, 5.0, 3.0, 2.0 ,1.0])
points

tensor([4., 1., 5., 3., 2., 1.])

In [11]:
float(points[0]), float(points[1])

(4.0, 1.0)

In [12]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [13]:
points.shape

torch.Size([3, 2])

In [14]:
points= torch.zeros(3, 2)
points

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [15]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])

In [16]:
points[0, 1]

tensor(1.)

In [17]:
points[0]

tensor([4., 1.])