## 3.12 序列化张量

In [40]:
import torch
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])

In [41]:
torch.save(points, '../../data/plch3/ourpoints.t')

In [42]:
with open('../../data/plch3/ourpoints.t', 'wb') as f:
    torch.save(points, f)

In [43]:
points = torch.load('../../data/plch3/ourpoints.t')
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [44]:
with open('../../data/plch3/ourpoints.t', 'rb') as f:
    points = torch.load(f)
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

### 用h5py序列化到HDF5

In [45]:
conda install h5py

Solving environment: | 
  - https://repo.anaconda.com/pkgs/main/linux-64/linux-64::bzip2-1.0.8-h7b6447c_0, https://repo.anaconda.com/pkgs/main/linux-64/linux-64::libuuid-1.41.5-h5eee18b_0, https://repo.anaconda.com/pkgs/main/noarch/noarch::jsonpointer-2.1-pyhd3eb1b0_0, https://repo.anaconda.com/pkgs/main/noarch/noarch::tzdata-2023c-h04d1e81_0
  - defaults/noarch::tzdata-2023c-h04d1e81_0, https://repo.anaconda.com/pkgs/main/linux-64/linux-64::bzip2-1.0.8-h7b6447c_0, https://repo.anaconda.com/pkgs/main/linux-64/linux-64::libuuid-1.41.5-h5eee18b_0, https://repo.anaconda.com/pkgs/main/noarch/noarch::jsonpointer-2.1-pyhd3eb1b0_0
  - defaults/linux-64::bzip2-1.0.8-h7b6447c_0, https://repo.anaconda.com/pkgs/main/linux-64/linux-64::libuuid-1.41.5-h5eee18b_0, https://repo.anaconda.com/pkgs/main/noarch/noarch::jsonpointer-2.1-pyhd3eb1b0_0, https://repo.anaconda.com/pkgs/main/noarch/noarch::tzdata-2023c-h04d1e81_0
  - defaults/linux-64::bzip2-1.0.8-h7b6447c_0, defaults/noarch::tzdata-2023c-h04d1e

In [46]:
import h5py

f = h5py.File('../../data/plch3/ourpoints.hdf5', 'w')
dset = f.create_dataset('coords', data=points.numpy())
f.close()

In [49]:
f = h5py.File('../../data/plch3/ourpoints.hdf5', 'r')
dset = f['coords']
last_points = dset[-2:]
last_points

array([[5., 3.],
       [2., 1.]], dtype=float32)

In [50]:
last_points = torch.from_numpy(dset[-2:])
f.close()
last_points

tensor([[5., 3.],
        [2., 1.]])