In [1]:
## 3.3 索引张量

In [2]:
import torch

In [7]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [4]:
points[1:]

tensor([[5., 3.],
        [2., 1.]])

In [5]:
points[1:, :]

tensor([[5., 3.],
        [2., 1.]])

In [8]:
points[1:, 0]

tensor([5., 2.])

In [9]:
points[None]

tensor([[[4., 1.],
         [5., 3.],
         [2., 1.]]])