## 3.8 张量元数据：大小、偏移量和步长

### 3.8.1 另一个张量的存储视图

In [1]:
import torch

In [2]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point = points[1]
second_point.storage_offset()

2

In [3]:
second_point.size()

torch.Size([2])

In [4]:
second_point.shape

torch.Size([2])

In [5]:
points.stride()

(2, 1)

In [6]:
second_point = points[1]
second_point.size()

torch.Size([2])

In [7]:
second_point.storage_offset()

2

In [8]:
second_point.stride()

(1,)

In [9]:
points = torch.tensor([[4.0,1.0], [5.0, 3.0], [2.0, 1.0]])
second_point = points[1]
second_point[0] = 10.0
points

tensor([[ 4.,  1.],
        [10.,  3.],
        [ 2.,  1.]])

In [10]:
points = torch.tensor([[4.0,1.0], [5.0, 3.0], [2.0, 1.0]])
second_point = points[1].clone()
second_point[0] = 10.0
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

### 3.8.2 无复制转置

In [11]:
points = torch.tensor([[4.0,1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [12]:
points_t = points.t()
points_t

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [13]:
id(points.storage()) == id(points_t.storage())

/tmp/ipykernel_767/2282178668.py:1: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  id(points.storage()) == id(points_t.storage())


True

In [14]:
points.stride()

(2, 1)

In [15]:
points_t.stride()

(1, 2)

### 3.8.3 高维转置

In [16]:
some_t = torch.ones(3, 4, 5)
transpose_t = some_t.transpose(0, 2)
some_t.shape

torch.Size([3, 4, 5])

In [17]:
transpose_t.shape

torch.Size([5, 4, 3])

In [18]:
some_t.stride()

(20, 5, 1)

In [25]:
transpose_t.stride()

(1, 5, 20)

### 3.8.4 连续张量

In [27]:
points.is_contiguous()

True

In [28]:
points_t.is_contiguous()

False

In [29]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points_t = points.t()
points_t

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [31]:
points_t.storage()

/tmp/ipykernel_767/3158410579.py:1: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  points_t.storage()
/root/.local/lib/python3.8/site-packages/IPython/lib/pretty.py:778: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  output = repr(obj)
/usr/local/miniconda3/lib/python3.8/site-packages/torch/storage.py:645: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedSt

 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

In [32]:
points_t.stride()

(1, 2)

In [33]:
points_t_cont = points_t.contiguous()
points_t_cont

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [34]:
points_t_cont.stride()

(3, 1)

In [35]:
points_t_cont.storage()

/tmp/ipykernel_767/1562932398.py:1: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  points_t_cont.storage()
/root/.local/lib/python3.8/site-packages/IPython/lib/pretty.py:778: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  output = repr(obj)
/usr/local/miniconda3/lib/python3.8/site-packages/torch/storage.py:645: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access Unty

 4.0
 5.0
 2.0
 1.0
 3.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]